sudo: required
dist: trusty

language: rust
rust:
  - stable
  - beta
  - nightly

python:
  - "3.5"
  # - "nightly" # currently points to 3.7-dev
  - "pypy"

matrix:
  include:
    - os: osx
    - os: linux

  allow_failures:
    - rust: nightly


addons:
  apt:
    sources:
      - deadsnakes      # for python 3.5
    packages:
      - build-essential
      - python3.5
      - python3.5-dev
      - libc6



install:
  - pip install wheel
# install:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

#
# defaults
#
# script:
# - cargo build --verbose
# - cargo test --verbose

script:
  - cargo build --verbose
  - cargo test --verbose
  - make wheel

after_script:
  - ls -la tmp/wheels


notifications:
  email: false
