sudo: required
dist: trusty

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    sources:
      - deadsnakes      # for python 3.5
    packages:
      - build-essential
      - python3.5
      - python3.5-dev
      - libc6

notifications:
  email: false
# script: make all
# cargo build --verbose
# cargo test --verbose
