# sudo: required
sudo: false
dist: trusty
language: python

env:
  - RUST = nightly  # stable beta nightly
#   global:
#     - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

matrix:
  include:
    # - os: osx
    #   language: python
    #   python: "3.5"
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    # - os: linux
    #   python: "pypy3.5-5.8.0"
      # sudo: required
      # services:
      #   - docker
      # env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

  allow_failures:
    - os: osx
    #   - rust: nightly


addons:
  apt:
    sources:
      - deadsnakes      # for python 3.5
    packages:
      - build-essential
      - libc6
      - mmv
      - python-dev
      # - python3.5
      # - python3.5-dev

before_install:
  - which python
  - which python3
  - python -V
  - ls /opt/python/

install:
  - pip install wheel
  - curl -sL https://static.rust-lang.org/rustup.sh -o ~/rustup.sh
  - sh ~/rustup.sh --prefix=/usr/local --spec=$RUST -y 2> /dev/null
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/python/3.6/lib:/opt/python/3.5/lib:/opt/python/2.7/lib
  # - curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh
  # - sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=stable -y --disable-sudo 2> /dev/null
  # - curl https://sh.rustup.rs -sSf | sh -s -- -y
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/python/3.6/lib
  - cargo test --verbose --release
  # - RUSTFLAGS='-C target-feature=-crt-static' python setup.py bdist_wheel  # for musl
  - python setup.py bdist_wheel
  # - (cd build/lib/; python -c "import rparser")
  # - (cd rparser; ln -sf ../build/lib/rparser/librparser.so librparser.so)
  - cp -f target/release/librparser.so rparser.so
  - python -c 'import rparser;print(rparser.__version__)'
  - python setup.py test
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh $TRAVIS_OS_NAME; fi
  # - ls wheelhouse/

# after_script:
  # - mmv "dist/rparser-*-cp*-cp*-manylinux1_*.whl" "/io/wheelhouse/rust_fst-#1-py2.py3-none-manylinux1_#4.whl"
# https://www.python.org/dev/peps/pep-0427/#file-name-convention

# Rename wheel to accept in pypi. Pypi does not accept "linux_x86-64"
#
# After compilation we have:
#
#   rparser-0.1.19-cp36-cp36m-linux_x86_64.whl
#   Django-1.10.4-py2.py3-none-any.whl           Example (Django)
#
# Only py3: Name-1.10.4-py3-none-any.whl
before_deploy:
  - pip install twine
  - ls -la dist
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then mmv "dist/rparser-*-*-*-*_*.whl" "dist/rparser-#1-py27-none-any.whl"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then mmv "dist/rparser-*-*-*-*_*.whl" "dist/rparser-#1-py35-none-any.whl"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then mmv "dist/rparser-*-*-*-*_*.whl" "dist/rparser-#1-py36-none-any.whl"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy3* ]]; then mmv "dist/rparser-*-*-*-*_*.whl" "dist/rparser-#1-pp358-pypy3_58-any.whl"; fi
  # pp358-pypy3_58-manylinux1_x86_64.whl
  # - mmv "dist/rparser-*-*-*-*_*.whl" "dist/rparser-#1-py2.py3-none-any.whl"
  - ls -la dist


# To use encrypted variables:
#
# sudo gem install travis
# travis encrypt MY_SECRET_ENV=super_secret --add env.matrix
# travis encrypt MY_SECRET_ENV=super_secret -r pashinin-com/parser
#
# The travis slug is stored in .git/config. You can change it there
# instead of constantly using the -r option.
#
# You need to register your package first before deploying will work:
#
# python3 setup.py bdist_wheel
# twine upload dist/rparser-0.1.1-cp35-cp35m-linux_x86_64.whl
deploy:
  - provider: pypi
    user: pashinin
    password:
      secure: "t/CzlbFJSbjxY6AnzC6DKWGNtVjHR0vbTMde4efncw6StTzUWoG/INNng92KloQk9p73i1o1wAd2ZV3sZYh5QiGiN2u1SoeIaVY+vPQyphVpbCWLw9jVuEeSOJCbMM/zxE0xDayiGc6Oiy9nYLXFeLHMSiMDyJJZSzkrAefzoJN8J7P5IJ3hIQ4P177IHS9y4m8hWBWLjWwOoicAHZMoAweTf01kRDEdChsf7NKa7lIiQ563Wf9Z5QvJL+/qum/+yUwzz+I+PumuI6CfAMgifwX7JDjt9X351K6rUtWhu/K5zaqSFLbHfuP4LBSjsGDQG+PyK/6592DjpzzFxIE16mf9+WqJ0gBs1T4RKuv74PRJQjEg1X/IjOggRtv/o1/gIGHtiM3NR54FL7s6cQtYHAfbTvyM7lekR+QcYn4LoVEQTZKkVgAkKB5ukMZDeCdW1tPfc+ElRAbMBb35AIpD5wPvq67IApVYd5dP4ApAasFsEHHe3XYHW5SGrv7T/+wVgA1Dl/NxJp+Snh3lkT9wcziwTlg4ALMF9exqsZ5KQepbOUsvmRM8UEuyp2XJ7q3MnYUOciwFsuNIxhxNnOO0YA2R5M08XQrmqBFUJ+upDSBEZEFyqJtKo1BBr6CPoRVMFdK+AyM1uhwDJyO1FuARdYUfv9Yi8+jr0QPQ2ibDBuw="
    skip_cleanup: true
    skip_upload_docs: true
    on:
      tags: true
      # python: 3.6
      # repo: pashinin-com/parser


notifications:
  email: false
